const nationCode = [{"KName":"가나","Ename":"Ghana","Pnum":233,"Code2":"GH","Code3":"GHA"},
    {"KName":"가봉","Ename":"Gabon","Pnum":241,"Code2":"GA","Code3":"GAB"},
    {"KName":"가이아나","Ename":"Guyana","Pnum":592,"Code2":"GY","Code3":"GUY"},
    {"KName":"감비아","Ename":"Gambia","Pnum":220,"Code2":"GM","Code3":"GMB"},
    {"KName":"괌","Ename":"Guam","Pnum":1671,"Code2":"GU","Code3":"GUM"},
    {"KName":"과들루프","Ename":"Guadeloupe","Pnum":590,"Code2":"GP","Code3":"GLP"},
    {"KName":"과테말라","Ename":"Guatemala","Pnum":502,"Code2":"GT","Code3":"GTM"},
    {"KName":"그레나다","Ename":"Grenada","Pnum":1473,"Code2":"GD","Code3":"GRD"},
    {"KName":"그리스","Ename":"Greece","Pnum":30,"Code2":"GR","Code3":"GRC"},
    {"KName":"그린란드","Ename":"Greenland","Pnum":299,"Code2":"GL","Code3":"GRL"},
    {"KName":"기니","Ename":"Guinea","Pnum":224,"Code2":"GN","Code3":"GIN"},
    {"KName":"기니비사우","Ename":"Guinea-Bissau","Pnum":245,"Code2":"GW","Code3":"GNB"},
    {"KName":"나미비아","Ename":"Namibia","Pnum":264,"Code2":"NA","Code3":"NAM"},
    {"KName":"나우루","Ename":"Nauru","Pnum":674,"Code2":"NR","Code3":"NRU"},
    {"KName":"나이지리아","Ename":"Nigeria","Pnum":234,"Code2":"NG","Code3":"NGA"},
    {"KName":"남수단","Ename":"South Sudan","Pnum":211,"Code2":"SS","Code3":"SSD"},
    {"KName":"남아프리카 공화국","Ename":"South Africa","Pnum":27,"Code2":"ZA","Code3":"ZAF"},
    {"KName":"네덜란드","Ename":"the Netherlands","Pnum":31,"Code2":"NL","Code3":"NLD"},
    {"KName":"네팔","Ename":"Nepal","Pnum":977,"Code2":"NP","Code3":"NPL"},
    {"KName":"노르웨이","Ename":"Norway","Pnum":47,"Code2":"NO","Code3":"NOR"},
    {"KName":"누벨칼레도니","Ename":"New Caledonia","Pnum":687,"Code2":"NC","Code3":"NCL"},
    {"KName":"뉴질랜드","Ename":"New Zealand","Pnum":64,"Code2":"NZ","Code3":"NZL"},
    {"KName":"니우에","Ename":"Niue","Pnum":683,"Code2":"NU","Code3":"NIU"},
    {"KName":"니제르","Ename":"Niger","Pnum":227,"Code2":"NE","Code3":"NER"},
    {"KName":"니카라과","Ename":"Nicaragua","Pnum":505,"Code2":"NI","Code3":"NIC"},
    {"KName":"대한민국","Ename":"Republic of Korea","Pnum":82,"Code2":"KR","Code3":"KOR"},
    {"KName":"덴마크","Ename":"Denmark","Pnum":45,"Code2":"DK","Code3":"DNK"},
    {"KName":"도미니카 공화국","Ename":"Dominican R.","Pnum":1809,"Code2":"DO","Code3":"DOM"},
    {"KName":"도미니카 연방","Ename":"Dominica","Pnum":1767,"Code2":"DM","Code3":"DMA"},
    {"KName":"독일","Ename":"Germany","Pnum":49,"Code2":"DE","Code3":"DEU"},
    {"KName":"동티모르","Ename":"East Timor","Pnum":670,"Code2":"TL","Code3":"TLS"},
    {"KName":"라오스","Ename":"Laos","Pnum":856,"Code2":"LA","Code3":"LAO"},
    {"KName":"라이베리아","Ename":"Liberia","Pnum":231,"Code2":"LR","Code3":"LBR"},
    {"KName":"라트비아","Ename":"Latvia","Pnum":371,"Code2":"LV","Code3":"LVA"},
    {"KName":"러시아","Ename":"Russia","Pnum":7,"Code2":"RU","Code3":"RUS"},
    {"KName":"레바논","Ename":"Lebanon","Pnum":961,"Code2":"LB","Code3":"LBN"},
    {"KName":"레소토","Ename":"Lesotho","Pnum":266,"Code2":"LS","Code3":"LSO"},
    {"KName":"루마니아","Ename":"Romania","Pnum":40,"Code2":"RO","Code3":"ROU"},
    {"KName":"룩셈부르크","Ename":"Luxembourg","Pnum":352,"Code2":"LU","Code3":"LUX"},
    {"KName":"르완다","Ename":"Rwanda","Pnum":250,"Code2":"RW","Code3":"RWA"},
    {"KName":"리비아","Ename":"Libya","Pnum":218,"Code2":"LY","Code3":"LBY"},
    {"KName":"리투아니아","Ename":"Lithuania","Pnum":370,"Code2":"LT","Code3":"LTU"},
    {"KName":"리히텐슈타인","Ename":"Liechtenstein","Pnum":423,"Code2":"LI","Code3":"LIE"},
    {"KName":"마다가스카르","Ename":"Madagascar","Pnum":261,"Code2":"MG","Code3":"MDG"},
    {"KName":"마르티니크","Ename":"Martinique","Pnum":596,"Code2":"MQ","Code3":"MTQ"},
    {"KName":"마셜 제도","Ename":"Marshall Islands","Pnum":692,"Code2":"MH","Code3":"MHL"},
    {"KName":"마요트","Ename":"Mayotte","Pnum":269,"Code2":"YT","Code3":"MYT"},
    {"KName":"마카오","Ename":"Macao","Pnum":853,"Code2":"MO","Code3":"MAC"},
    {"KName":"말라위","Ename":"Malawi","Pnum":265,"Code2":"MW","Code3":"MWI"},
    {"KName":"말레이시아","Ename":"Malaysia","Pnum":60,"Code2":"MY","Code3":"MYS"},
    {"KName":"말리","Ename":"Mali","Pnum":223,"Code2":"ML","Code3":"MLI"},
    {"KName":"멕시코","Ename":"Mexico","Pnum":52,"Code2":"MX","Code3":"MEX"},
    {"KName":"모나코","Ename":"Monaco","Pnum":377,"Code2":"MC","Code3":"MCO"},
    {"KName":"모로코","Ename":"Morocco","Pnum":212,"Code2":"MA","Code3":"MAR"},
    {"KName":"모리셔스","Ename":"Mauritius","Pnum":230,"Code2":"MU","Code3":"MUS"},
    {"KName":"모리타니","Ename":"Mauritania","Pnum":222,"Code2":"MR","Code3":"MRT"},
    {"KName":"모잠비크","Ename":"Mozambique","Pnum":258,"Code2":"MZ","Code3":"MOZ"},
    {"KName":"몬테네그로","Ename":"Montenegro","Pnum":382,"Code2":"ME","Code3":"MNE"},
    {"KName":"몬트세랫","Ename":"Montserrat","Pnum":1664,"Code2":"MS","Code3":"MSR"},
    {"KName":"몰도바","Ename":"Maldova","Pnum":373,"Code2":"MD","Code3":"MDA"},
    {"KName":"몰디브","Ename":"Maldives","Pnum":960,"Code2":"MV","Code3":"MDV"},
    {"KName":"몰타","Ename":"Malta","Pnum":356,"Code2":"MT","Code3":"MLT"},
    {"KName":"몽골","Ename":"Mongolia","Pnum":976,"Code2":"MN","Code3":"MNG"},
    {"KName":"미국","Ename":"United States of America","Pnum":1,"Code2":"US","Code3":"USA"},
    {"KName":"미얀마(버마","Ename":"Myanmar","Pnum":95,"Code2":"MM","Code3":"MMR"},
    {"KName":"미크로네시아 연방","Ename":"Micronesia","Pnum":691,"Code2":"FM","Code3":"FSM"},
    {"KName":"바누아투","Ename":"Vanuatu","Pnum":678,"Code2":"VU","Code3":"VUT"},
    {"KName":"바레인","Ename":"Bahrain","Pnum":973,"Code2":"BH","Code3":"BHR"},
    {"KName":"바베이도스","Ename":"Barbados","Pnum":1246,"Code2":"BB","Code3":"BRB"},
    {"KName":"바티칸 시국","Ename":"Vatican","Pnum":379,"Code2":"VA","Code3":"VAT"},
    {"KName":"바하마","Ename":"Bahamas","Pnum":1242,"Code2":"BS","Code3":"BHS"},
    {"KName":"방글라데시","Ename":"Bangladesh","Pnum":880,"Code2":"BD","Code3":"BGD"},
    {"KName":"버뮤다","Ename":"Bermuda","Pnum":1441,"Code2":"BM","Code3":"BMU"},
    {"KName":"베냉","Ename":"Benin","Pnum":229,"Code2":"BJ","Code3":"BEN"},
    {"KName":"베네수엘라","Ename":"Venezuela","Pnum":58,"Code2":"VE","Code3":"VEN"},
    {"KName":"베트남","Ename":"Vietnam","Pnum":84,"Code2":"VN","Code3":"VNM"},
    {"KName":"벨기에","Ename":"Belgium","Pnum":32,"Code2":"BE","Code3":"BEL"},
    {"KName":"벨라루스","Ename":"Belarus","Pnum":375,"Code2":"BY","Code3":"BLR"},
    {"KName":"벨리즈","Ename":"Belize","Pnum":501,"Code2":"BZ","Code3":"BLZ"},
    {"KName":"보스니아 헤르체고비나","Ename":"Bosnia and Herzegovina","Pnum":387,"Code2":"BA","Code3":"BIH"},
    {"KName":"보츠와나","Ename":"Botswana","Pnum":267,"Code2":"BW","Code3":"BWA"},
    {"KName":"볼리비아","Ename":"Bolivia","Pnum":591,"Code2":"BO","Code3":"BOL"},
    {"KName":"부룬디","Ename":"Burundi","Pnum":257,"Code2":"BI","Code3":"BDI"},
    {"KName":"부르키나파소","Ename":"Burkina Faso","Pnum":226,"Code2":"BF","Code3":"BFA"},
    {"KName":"부탄","Ename":"Bhutan","Pnum":975,"Code2":"BT","Code3":"BTN"},
    {"KName":"북마케도니아","Ename":"Macedonia","Pnum":389,"Code2":"MK","Code3":"MKD"},
    {"KName":"불가리아","Ename":"Bulgaria","Pnum":359,"Code2":"BG","Code3":"BGR"},
    {"KName":"브라질","Ename":"Brazil","Pnum":55,"Code2":"BR","Code3":"BRA"},
    {"KName":"브루나이","Ename":"Brunei","Pnum":673,"Code2":"BN","Code3":"BRN"},
    {"KName":"사모아","Ename":"Samoa","Pnum":685,"Code2":"WS","Code3":"WSM"},
    {"KName":"사우디아라비아","Ename":"Saudi Arabia","Pnum":966,"Code2":"SA","Code3":"SAU"},
    {"KName":"산마리노","Ename":"San Marino","Pnum":378,"Code2":"SM","Code3":"SMR"},
    {"KName":"생피에르 미클롱","Ename":"Saint Pierre and Miquelon","Pnum":508,"Code2":"PM","Code3":"SPM"},
    {"KName":"서사하라","Ename":"Western Sahara","Pnum":212,"Code2":"EH","Code3":"ESH"},
    {"KName":"세네갈","Ename":"Senegal","Pnum":221,"Code2":"SN","Code3":"SEN"},
    {"KName":"세르비아","Ename":"Serbia","Pnum":381,"Code2":"RS","Code3":"SRB"},
    {"KName":"세이셸","Ename":"Seychelles","Pnum":248,"Code2":"SC","Code3":"SYC"},
    {"KName":"세인트루시아","Ename":"Saint Lucia","Pnum":1758,"Code2":"LC","Code3":"LCA"},
    {"KName":"세인트헬레나","Ename":"Saint Helena","Pnum":290,"Code2":"SH","Code3":"SHN"},
    {"KName":"소말리아","Ename":"Somalia","Pnum":252,"Code2":"SO","Code3":"SOM"},
    {"KName":"솔로몬 제도","Ename":"Solomon Islands","Pnum":677,"Code2":"SB","Code3":"SLB"},
    {"KName":"수단","Ename":"Sudan","Pnum":249,"Code2":"SD","Code3":"SDN"},
    {"KName":"수리남","Ename":"Suriname","Pnum":597,"Code2":"SR","Code3":"SUR"},
    {"KName":"스리랑카","Ename":"Sri Lanka","Pnum":94,"Code2":"LK","Code3":"LKA"},
    {"KName":"스웨덴","Ename":"Sweden","Pnum":46,"Code2":"SE","Code3":"SWE"},
    {"KName":"스위스","Ename":"Switzerland","Pnum":41,"Code2":"CH","Code3":"CHE"},
    {"KName":"스페인","Ename":"Spain","Pnum":34,"Code2":"ES","Code3":"ESP"},
    {"KName":"슬로바키아","Ename":"Slovakia","Pnum":421,"Code2":"SK","Code3":"SVK"},
    {"KName":"슬로베니아","Ename":"Slovenia","Pnum":386,"Code2":"SI","Code3":"SVN"},
    {"KName":"시리아","Ename":"Syria","Pnum":963,"Code2":"SY","Code3":"SYR"},
    {"KName":"시에라리온","Ename":"Sierra Leone","Pnum":232,"Code2":"SL","Code3":"SLE"},
    {"KName":"신트마르턴","Ename":"Sint Maarten","Pnum":1721,"Code2":"SX","Code3":"SXM"},
    {"KName":"싱가포르","Ename":"Singapore","Pnum":65,"Code2":"SG","Code3":"SGP"},
    {"KName":"아랍에미리트","Ename":"United Arab Emirates","Pnum":971,"Code2":"AE","Code3":"ARE"},
    {"KName":"아루바","Ename":"Aruba","Pnum":297,"Code2":"AW","Code3":"ABW"},
    {"KName":"아르메니아","Ename":"Armenia","Pnum":374,"Code2":"AM","Code3":"ARM"},
    {"KName":"아르헨티나","Ename":"Argentina","Pnum":54,"Code2":"AR","Code3":"ARG"},
    {"KName":"아메리칸사모아","Ename":"American Samoa","Pnum":1684,"Code2":"AS","Code3":"ASM"},
    {"KName":"아이슬란드","Ename":"Iceland","Pnum":354,"Code2":"IS","Code3":"ISL"},
    {"KName":"아이티","Ename":"Haiti","Pnum":509,"Code2":"HT","Code3":"HTI"},
    {"KName":"아일랜드","Ename":"Ireland","Pnum":353,"Code2":"IE","Code3":"IRL"},
    {"KName":"아제르바이잔","Ename":"Azerbaijan","Pnum":994,"Code2":"AZ","Code3":"AZE"},
    {"KName":"아프가니스탄","Ename":"Afghanistan","Pnum":93,"Code2":"AF","Code3":"AFG"},
    {"KName":"안도라","Ename":"Andorra","Pnum":376,"Code2":"AD","Code3":"AND"},
    {"KName":"알바니아","Ename":"Albania","Pnum":355,"Code2":"AL","Code3":"ALB"},
    {"KName":"알제리","Ename":"Algeria","Pnum":213,"Code2":"DZ","Code3":"DZA"},
    {"KName":"앙골라","Ename":"Angola","Pnum":244,"Code2":"AO","Code3":"AGO"},
    {"KName":"앤티가 바부다","Ename":"Antigua and Barbuda","Pnum":1268,"Code2":"AG","Code3":"ATG"},
    {"KName":"앵귈라","Ename":"Anguilla","Pnum":1264,"Code2":"AI","Code3":"AIA"},
    {"KName":"에리트레아","Ename":"Eritrea","Pnum":291,"Code2":"ER","Code3":"ERI"},
    {"KName":"에스와티니","Ename":"Eswatini","Pnum":268,"Code2":"SZ","Code3":"SWZ"},
    {"KName":"에스토니아","Ename":"Estonia","Pnum":372,"Code2":"EE","Code3":"EST"},
    {"KName":"에콰도르","Ename":"Ecuador","Pnum":593,"Code2":"EC","Code3":"ECU"},
    {"KName":"에티오피아","Ename":"Ethiopia","Pnum":251,"Code2":"ET","Code3":"ETH"},
    {"KName":"엘살바도르","Ename":"El Salvador","Pnum":503,"Code2":"SV","Code3":"SLV"},
    {"KName":"영국","Ename":"United Kingdom","Pnum":44,"Code2":"GB","Code3":"GBR"},
    {"KName":"예멘","Ename":"Yemen","Pnum":967,"Code2":"YE","Code3":"YEM"},
    {"KName":"오만","Ename":"Oman","Pnum":968,"Code2":"OM","Code3":"OMN"},
    {"KName":"오스트레일리아","Ename":"Australia","Pnum":61,"Code2":"AU","Code3":"AUS"},
    {"KName":"오스트리아","Ename":"Austria","Pnum":43,"Code2":"AT","Code3":"AUT"},
    {"KName":"온두라스","Ename":"Honduras","Pnum":504,"Code2":"HN","Code3":"HND"},
    {"KName":"요르단","Ename":"Jordan","Pnum":962,"Code2":"JO","Code3":"JOR"},
    {"KName":"우간다","Ename":"Uganda","Pnum":256,"Code2":"UG","Code3":"UGA"},
    {"KName":"우루과이","Ename":"Uruguay","Pnum":598,"Code2":"UY","Code3":"URY"},
    {"KName":"우즈베키스탄","Ename":"Uzbekistan","Pnum":998,"Code2":"UZ","Code3":"UZB"},
    {"KName":"우크라이나","Ename":"Ukraine","Pnum":380,"Code2":"UA","Code3":"UKR"},
    {"KName":"이라크","Ename":"Iraq","Pnum":964,"Code2":"IR","Code3":"IRN"},
    {"KName":"이란","Ename":"Iran","Pnum":98,"Code2":"IQ","Code3":"IRQ"},
    {"KName":"이스라엘","Ename":"Israel","Pnum":972,"Code2":"IL","Code3":"ISR"},
    {"KName":"이집트","Ename":"Egypt","Pnum":20,"Code2":"EG","Code3":"EGY"},
    {"KName":"이탈리아","Ename":"Italy","Pnum":39,"Code2":"IT","Code3":"ITA"},
    {"KName":"인도","Ename":"India","Pnum":91,"Code2":"IN","Code3":"IND"},
    {"KName":"인도네시아","Ename":"Indonesia","Pnum":62,"Code2":"ID","Code3":"IDN"},
    {"KName":"일본","Ename":"Japan","Pnum":81,"Code2":"JP","Code3":"JPN"},
    {"KName":"자메이카","Ename":"Jamaica","Pnum":1876,"Code2":"JM","Code3":"JAM"},
    {"KName":"잠비아","Ename":"Zambia","Pnum":260,"Code2":"ZM","Code3":"ZMB"},
    {"KName":"적도 기니","Ename":"Equatorial Guinea","Pnum":240,"Code2":"GQ","Code3":"GNQ"},
    {"KName":"북한","Ename":"DPR of Korea","Pnum":850,"Code2":"KP","Code3":"PRK"},
    {"KName":"조지아","Ename":"Georgia","Pnum":995,"Code2":"GE","Code3":"GEO"},
    {"KName":"중앙아프리카 공화국","Ename":"Central Africa","Pnum":236,"Code2":"CF","Code3":"CAF"},
    {"KName":"대만","Ename":"Taiwan","Pnum":886,"Code2":"TW","Code3":"TWN"},
    {"KName":"중화인민공화국","Ename":"China","Pnum":86,"Code2":"CN","Code3":"CHN"},
    {"KName":"지부티","Ename":"Djibouti","Pnum":253,"Code2":"DJ","Code3":"DJI"},
    {"KName":"지브롤터","Ename":"Gibraltar","Pnum":350,"Code2":"GI","Code3":"GIB"},
    {"KName":"짐바브웨","Ename":"Zimbabwe","Pnum":263,"Code2":"ZW","Code3":"ZWE"},
    {"KName":"차드","Ename":"Chad","Pnum":235,"Code2":"TD","Code3":"TCD"},
    {"KName":"체코","Ename":"Czech","Pnum":420,"Code2":"CZ","Code3":"CZE"},
    {"KName":"칠레","Ename":"Chile","Pnum":56,"Code2":"CL","Code3":"CHL"},
    {"KName":"카메룬","Ename":"Cameroon","Pnum":237,"Code2":"CM","Code3":"CMR"},
    {"KName":"카보베르데","Ename":"Cape Verde","Pnum":238,"Code2":"CV","Code3":"CPV"},
    {"KName":"카자흐스탄","Ename":"Kazakstan","Pnum":7,"Code2":"KZ","Code3":"KAZ"},
    {"KName":"카타르","Ename":"Qatar","Pnum":974,"Code2":"QA","Code3":"QAT"},
    {"KName":"캄보디아","Ename":"Cambodia","Pnum":855,"Code2":"KH","Code3":"KHM"},
    {"KName":"캐나다","Ename":"Canada","Pnum":1,"Code2":"CA","Code3":"CAN"},
    {"KName":"케냐","Ename":"Kenya","Pnum":254,"Code2":"KE","Code3":"KEN"},
    {"KName":"케이맨 제도","Ename":"Cayman Islands","Pnum":1345,"Code2":"KY","Code3":"CYM"},
    {"KName":"코모로","Ename":"the Comoros","Pnum":269,"Code2":"KM","Code3":"COM"},
    {"KName":"코스타리카","Ename":"Costa Rica","Pnum":506,"Code2":"CR","Code3":"CRI"},
    {"KName":"코트디부아르","Ename":"Ivory Coast","Pnum":225,"Code2":"CI","Code3":"CIV"},
    {"KName":"콜롬비아","Ename":"Colombia","Pnum":57,"Code2":"CO","Code3":"COL"},
    {"KName":"콩고 공화국","Ename":"Congo","Pnum":242,"Code2":"CG","Code3":"COG"},
    {"KName":"콩고 민주 공화국","Ename":"DR Congo","Pnum":243,"Code2":"CD","Code3":"COD"},
    {"KName":"쿠바","Ename":"Cuba","Pnum":53,"Code2":"CU","Code3":"CUB"},
    {"KName":"쿠웨이트","Ename":"Kuwait","Pnum":965,"Code2":"KW","Code3":"KWT"},
    {"KName":"쿡 제도","Ename":"Cook Islands","Pnum":682,"Code2":"CK","Code3":"COK"},
    {"KName":"크로아티아","Ename":"Croatia","Pnum":385,"Code2":"HR","Code3":"HRV"},
    {"KName":"키르기스스탄","Ename":"Kyrgizstan","Pnum":996,"Code2":"KG","Code3":"KGZ"},
    {"KName":"키리바시","Ename":"Kiribati","Pnum":686,"Code2":"KI","Code3":"KIR"},
    {"KName":"키프로스","Ename":"Cyprus","Pnum":357,"Code2":"CY","Code3":"CYP"},
    {"KName":"타지키스탄","Ename":"Tajikistan","Pnum":992,"Code2":"TJ","Code3":"TJK"},
    {"KName":"탄자니아","Ename":"Tanzania","Pnum":255,"Code2":"TZ","Code3":"TZA"},
    {"KName":"태국","Ename":"Thailand","Pnum":66,"Code2":"TH","Code3":"THA"},
    {"KName":"터키","Ename":"Turkey","Pnum":90,"Code2":"TR","Code3":"TUR"},
    {"KName":"토고","Ename":"Togo","Pnum":228,"Code2":"TG","Code3":"TGO"},
    {"KName":"토켈라우","Ename":"Tokelau","Pnum":690,"Code2":"TK","Code3":"TKL"},
    {"KName":"통가","Ename":"Tonga","Pnum":676,"Code2":"TO","Code3":"TON"},
    {"KName":"투르크메니스탄","Ename":"Turkmenistan","Pnum":993,"Code2":"TM","Code3":"TKM"},
    {"KName":"투발루","Ename":"Tuvalu","Pnum":688,"Code2":"TV","Code3":"TUV"},
    {"KName":"튀니지","Ename":"Tunisia","Pnum":216,"Code2":"TN","Code3":"TUN"},
    {"KName":"트리니다드 토바고","Ename":"Trinidad and Tobago","Pnum":1868,"Code2":"TT","Code3":"TTO"},
    {"KName":"파나마","Ename":"Panama","Pnum":507,"Code2":"PA","Code3":"PAN"},
    {"KName":"파라과이","Ename":"Paraguay","Pnum":595,"Code2":"PY","Code3":"PRY"},
    {"KName":"파키스탄","Ename":"Pakistan","Pnum":92,"Code2":"PK","Code3":"PAK"},
    {"KName":"파푸아뉴기니","Ename":"Papua New Guinea","Pnum":675,"Code2":"PG","Code3":"PNG"},
    {"KName":"팔라우","Ename":"Palau","Pnum":680,"Code2":"PW","Code3":"PLW"},
    {"KName":"팔레스타인","Ename":"State of Palestine","Pnum":970,"Code2":"PS","Code3":"PSE"},
    {"KName":"페루","Ename":"Peru","Pnum":51,"Code2":"PE","Code3":"PER"},
    {"KName":"포르투갈","Ename":"Portugal","Pnum":351,"Code2":"PT","Code3":"PRT"},
    {"KName":"포클랜드 제도","Ename":"Falkland Islands","Pnum":500,"Code2":"FK","Code3":"FLK"},
    {"KName":"폴란드","Ename":"Poland","Pnum":48,"Code2":"PL","Code3":"POL"},
    {"KName":"푸에르토리코","Ename":"Puerto Rico","Pnum":1787,"Code2":"PR","Code3":"PRI"},
    {"KName":"프랑스","Ename":"France","Pnum":33,"Code2":"FR","Code3":"FRA"},
    {"KName":"피지","Ename":"Fiji","Pnum":679,"Code2":"FJ","Code3":"FJI"},
    {"KName":"핀란드","Ename":"Finland","Pnum":358,"Code2":"FI","Code3":"FIN"},
    {"KName":"필리핀","Ename":"the Philippines","Pnum":63,"Code2":"PH","Code3":"PHL"},
    {"KName":"헝가리","Ename":"Hungary","Pnum":36,"Code2":"HU","Code3":"HUN"},
    {"KName":"홍콩","Ename":"Hong Kong","Pnum":852,"Code2":"HK","Code3":"HKG"}];